echo            both
log             ../DEM/log.init
# thermo_log      ../DEM/prev/thermo.txt

atom_style      granular
atom_modify     map array
communicate     single vel yes

boundary        f f f
newton          off
processors      2 2 1

units           si

region          reg block -0.01 0.01 -0.01 0.01 0.0 0.06 units box
create_box      1 reg

neighbor        0.0005 bin
neigh_modify    delay 0

# Material properties required for new pair styles
# hard_particles  yes
variable YoungsP equal 1.0e+7
variable PoissonsP equal 0.2
variable CoefRestitutionP equal 0.9
variable CoefFrictionP equal 0.844
variable CoefRollingFrictionP equal 0.261

fix             m1 all property/global youngsModulus peratomtype ${YoungsP}

fix             m2 all property/global poissonsRatio peratomtype ${PoissonsP}

fix             m3 all property/global coefficientRestitution peratomtypepair 1 ${CoefRestitutionP}

fix             m4 all property/global coefficientFriction peratomtypepair 1 ${CoefFrictionP}

fix             m5 all property/global coefficientRollingFriction peratomtypepair 1 ${CoefRollingFrictionP}

# pair style
pair_style      gran model hertz tangential history

#Hertzian without cohesion
pair_coeff      * *

# timestep, gravity
timestep        0.00001
fix             gravi all gravity 9.81 vector 0.0 0.0 -1.0

# walls
fix             zwalls1 all wall/gran model hertz tangential history primitive type 1 zplane 0.0
fix             zwalls2 all wall/gran model hertz tangential history primitive type 1 zplane 0.055
fix             cyclinderWall all wall/gran model hertz tangential history primitive type 1 zcylinder 0.0075 0.0 0.0

# region and particle insertion
variable pR equal 0.00025
variable pRho equal 2650
variable fR equal 0.0075-4*${pR}
variable fZ1 equal 0.001
variable fZ2 equal 0.054

region          factory cylinder z 0.0 0.0 ${fR} ${fZ1} ${fZ2} units box
fix             pts all particletemplate/sphere 15485863 atom_type 1 density constant ${pRho} radius constant ${pR}
fix             pdd all particledistribution/discrete 32452843 1 pts 1.0

fix             ins all insert/pack seed 49979687 distributiontemplate pdd vel constant 0. 0. 0. &
                insert_every once overlapcheck yes all_in yes particles_in_region 30000 region factory

# apply nve integration to all particles that are inserted as single particles
fix             integr all nve/sphere

# screen output
compute         rke all erotate/sphere
thermo_style    custom step atoms ke c_rke vol
thermo          1000
thermo_modify   lost ignore norm no
compute_modify  thermo_temp dynamic yes

# insert the first particles so that dump is not empty
dump            dmp all custom 1000 ../DEM/post/dump.init id type x y z ix iy iz vx vy vz fx fy fz omegax omegay omegaz radius

run             20000 upto

# **********************************************************************************************
# - write restart file
write_restart     ../DEM/prev/restart.init
