echo            both
log             ../DEM/log.run

atom_style      granular
atom_modify     map array
communicate     single vel yes

# For style f, the position of the face is fixed.
# If an atom moves outside the face it may be lost.
boundary        f f f
newton          off
units           si

# read restart file
read_restart    ../DEM/prev/restart.init

neighbor        0.0005 bin
neigh_modify    delay 0 one 10000

# **********************************************************************************************
# - define material properties required for new pair styles

# hard_particles  yes

variable        YoungsPP equal 5e+7
variable        YoungsWW equal 2e+7

variable        PoissonsPP equal 0.25
variable        PoissonsWW equal 0.3

variable        CoefRestitutionPP equal 0.9
variable        CoefRestitutionPW equal 0.9
variable        CoefRestitutionWW equal 1.0

variable        CoefFrictionPP equal 0.1545
variable        CoefFrictionPW equal 0.1333
variable        CoefFrictionWW equal 0.0

variable        CoefRollingFrictionPP equal 0.045
variable        CoefRollingFrictionPW equal 0.045
variable        CoefRollingFrictionWW equal 0.0

fix             m1 all property/global youngsModulus peratomtype &
                ${YoungsPP} ${YoungsWW}

fix             m2 all property/global poissonsRatio peratomtype &
                ${PoissonsPP} ${PoissonsWW}

fix             m3 all property/global coefficientRestitution peratomtypepair &
                2 ${CoefRestitutionPP} ${CoefRestitutionPW} ${CoefRestitutionPW} ${CoefRestitutionWW}

fix             m4 all property/global coefficientFriction peratomtypepair &
                2 ${CoefFrictionPP} ${CoefFrictionPW} ${CoefFrictionPW} ${CoefFrictionWW}

fix             m5 all property/global coefficientRollingFriction peratomtypepair &
                2 ${CoefRollingFrictionPP} ${CoefRollingFrictionPW} ${CoefRollingFrictionPW} ${CoefRollingFrictionWW}

# **********************************************************************************************
# - define mesh
fix             xwalls1 all wall/gran model hertz tangential history primitive type 2 xplane 0.0
fix             xwalls2 all wall/gran model hertz tangential history primitive type 2 xplane 0.04
fix             ywalls1 all wall/gran model hertz tangential history primitive type 2 yplane 0.0
fix             ywalls2 all wall/gran model hertz tangential history primitive type 2 yplane 0.04
fix             zwalls1 all wall/gran model hertz tangential history primitive type 2 zplane 0.0
fix             zwalls2 all wall/gran model hertz tangential history primitive type 2 zplane 0.2

# pair style
pair_style      gran model hertz tangential history

# Hertzian without cohesion
pair_coeff      * *

# **********************************************************************************************
# - define timestep, gravity
timestep        0.00001
fix             gravi all gravity 9.81 vector 0.0 0.0 -1.0

# apply nve integration to all particles that are inserted as single particles
fix             integr all nve/sphere

# **********************************************************************************************
# - define screen output
compute         rke all erotate/sphere
thermo_style    custom step atoms ke c_rke vol
thermo          1000
thermo_modify   lost ignore norm no
compute_modify  thermo_temp dynamic yes

# **********************************************************************************************
# - define dump
group           coarseParticles id < 4
group           fineParticles id >= 4
dump            dmp1 coarseParticles custom 5000 ../DEM/post/dump_coarseParticles.run &
                id type x y z ix iy iz vx vy vz fx fy fz omegax omegay omegaz radius
dump            dmp2 fineParticles custom 5000 ../DEM/post/dump_fineParticles.run &
                id type x y z ix iy iz vx vy vz fx fy fz omegax omegay omegaz radius

# **********************************************************************************************
# - define cfd coupling
fix           cfd1  all couple/cfd couple_every 100 mpi
fix           cfd2  all couple/cfd/force

run 1
