echo            both
log             ../DEM/log.init
thermo_log      ../DEM/prev/thermo.txt

atom_style      granular
atom_modify     map array
communicate     single vel yes

boundary        f f f
newton          off
processors      2 2 4

units           si

region          reg block -0.06 0.06 -0.06 0.06 0.0 0.9 units box
create_box      2 reg

neighbor        0.001 bin
neigh_modify    delay 0

# Material properties required for new pair styles
variable YoungsPP equal 1e+7
variable YoungsWW equal 1e+7

variable PoissonsPP equal 0.25
variable PoissonsWW equal 0.4

variable CoefRestitutionPP equal 0.5
variable CoefRestitutionPW equal 0.5
variable CoefRestitutionWW equal 1.0

variable CoefFrictionPP equal 0.1
variable CoefFrictionPW equal 0.3
variable CoefFrictionWW equal 0.0

variable CoefRollingFrictionPP equal 0.1
variable CoefRollingFrictionPW equal 0.1
variable CoefRollingFrictionWW equal 0.0

fix             m1 all property/global youngsModulus peratomtype &
                ${YoungsPP} ${YoungsWW}

fix             m2 all property/global poissonsRatio peratomtype &
                ${PoissonsPP} ${PoissonsWW}

fix             m3 all property/global coefficientRestitution peratomtypepair &
                2 ${CoefRestitutionPP} ${CoefRestitutionPW} ${CoefRestitutionPW} ${CoefRestitutionWW}

fix             m4 all property/global coefficientFriction peratomtypepair &
                2 ${CoefFrictionPP} ${CoefFrictionPW} ${CoefFrictionPW} ${CoefFrictionWW}

fix             m5 all property/global coefficientRollingFriction peratomtypepair &
                2 ${CoefRollingFrictionPP} ${CoefRollingFrictionPW} ${CoefRollingFrictionPW} ${CoefRollingFrictionWW}

# pair style
pair_style      gran model hertz tangential history

#Hertzian without cohesion
pair_coeff      * *

# timestep, gravity
timestep        0.00002
fix             gravi all gravity 9.81 vector 0.0 0.0 -1.0

# walls
fix             zwalls1 all wall/gran model hertz tangential history primitive type 2 zplane 0.0
fix             zwalls2 all wall/gran model hertz tangential history primitive type 2 zplane 0.8
fix             cyclinderWall all wall/gran model hertz tangential history primitive type 2 zcylinder 0.05 0.0 0.0

# region and particle insertion
variable pR equal 0.001
variable pRho equal 2500
variable fR equal 0.05-4*${pR}
variable fZ1 equal 0.05
variable fZ2 equal 0.75

region          factory cylinder z 0.0 0.0 ${fR} ${fZ1} ${fZ2} units box

fix             pts all particletemplate/sphere 15485863 atom_type 1 density constant ${pRho} &
                radius constant ${pR}

fix             pdd all particledistribution/discrete 32452843 1 pts 1.0

fix             ins all insert/pack seed 49979687 distributiontemplate pdd vel constant 0. 0. -0.1 insert_every once overlapcheck yes all_in yes particles_in_region 50000 region factory

# apply nve integration to all particles that are inserted as single particles
fix             integr all nve/sphere

# screen output
compute         rke all erotate/sphere
thermo_style    custom step atoms ke c_rke vol
thermo          1000
thermo_modify   lost ignore norm no
compute_modify  thermo_temp dynamic yes

# insert the first particles so that dump is not empty
dump            dmp all custom 1000 ../DEM/prev/dump.init id type x y z ix iy iz vx vy vz fx fy fz omegax omegay omegaz radius

run             60000 upto
write_restart   ../DEM/prev/restart.init
